#!/bin/bash
#
# Title:      Docker Uploader 
# Author(s):  PhyskX
# CoAuthot:   MrDoob
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'uploader'
        intport: '8080'
        extport: '7777'
    # CORE (MANDATORY) ############################################################
    - name: 'Including main job'
      include_tasks: './core.yml'

    - name: 'Including cleaner job'
      include_tasks: './cleaner.yml'

    - name: 'Including key and rclone job'
      include_tasks: './key.yml'
      
    - name: 'Remove Obsolete Cron'
      include_tasks: './cron.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'
          traefik.frontend.redirect.entryPoint: 'https'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}/:/config'
          - '/mnt/unionfs:/unionfs:shared'
          - '/mnt/move:/move:shared'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          TZ: '${TZ}'
          DISABLE_UNIONFS_CHOWN: 'true'
          DISABLE_TDRIVE1: 'true'
          DISABLE_TDRIVE2: 'true'
          DISABLE_GDRIVE: 'true'
          DISABLE_MERGERFS: 'true'

     ########## DEPLOYMENT ##########

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: 'physk/rclone-mergerfs'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        capabilities:
          - 'SYS_ADMIN'
        devices:
          - '/dev/fuse'
        privileged: true
        restart_policy: unless-stopped
        security_opts:
          - apparmor:unconfined
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
