#!/bin/bash
#
# This Docker image containerizes the deCONZ software from Dresden Elektronik, 
# which controls a ZigBee network using a Conbee USB or RaspBee GPIO serial interface. 
# This image runs deCONZ in "minimal" mode, for control of the ZigBee network via the
# WebUIs ("Wireless Light Control" and "Phoscon") and over the REST API and Websockets,
# and optionally runs a VNC server for viewing and interacting with the ZigBee mesh 
# through the deCONZ UI.
#
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'deconz'
        intport: '8100'
        extport: '8100'
        intport2: '8443'
        extport2: '8443'
        image: 'marthoc/deconz'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}:/root/.local/share/dresden-elektronik/deCONZ'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          DECONZ_DEVICE: '/dev/ttyACM0'
          DECONZ_VNC_MODE: '0'
          DECONZ_WEB_PORT: '8100'
          DECONZ_WS_PORT: '8443'
          DECONZ_UPNP: '0'
          DEBUG_INFO: '1'
          DEBUG_APS: '0'
          DEBUG_ZCL: '0'
          DEBUG_ZDP: '0'
          DEBUG_OTAU: '0'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
          - '{{ports.stdout}}{{extport2}}:{{intport2}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: always
        devices: '/dev/ttyACM0'
        network_mode: 'host'
        state: started
        labels: '{{pg_labels}}'
