#!/bin/bash
#
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'frdb'
        pgrole2: 'filerun'
        intport: '3306'
        extport: '3306'
        intport2: '80'
        extport2: '85'
        image: 'mariadb:10.1'
        image2: 'afian/filerun'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole2}}:/var/lib/mysql'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting {{pgrole2}} Volumes'
      set_fact:
        pg_volumes2:
          - '/opt/appdata/{{pgrole2}}/html:/var/www/html'
          - '/opt/appdata/{{pgrole2}}/user-files:/user-files'
          - 'mnt:/mnt'
          - 'opt:/opt'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          MYSQL_ROOT_PASSWORD: 'mysqlroot'
          MYSQL_USER: 'filerunuser'
          MYSQL_PASSWORD: 'filerunpass'
          MYSQL_DATABASE: 'filerun'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env2:
          PUID: '1000'
          PGID: '1000'
          FR_DB_HOST: 'frdb'
          FR_DB_PORT: '3306'
          FR_DB_NAME: 'filerun'
          FR_DB_USER: 'filerunuser'
          FR_DB_PASS: 'filerunpass'
          APACHE_RUN_USER: 'www-data'
          APACHE_RUN_USER_ID: '33'
          APACHE_RUN_GROUP: 'www-data'
          APACHE_RUN_GROUP_ID: '33'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: always
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started

    - name: 'Deploying {{pgrole2}}'
      docker_container:
        name: '{{pgrole2}}'
        image: '{{image2}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport2}}:{{intport2}}'
        volumes: '{{pg_volumes2}}'
        env: '{{pg_env2}}'
        restart_policy: unless-stopped
        links:
          - 'frdb:frdb'
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole2}}'
        state: started
        labels: '{{pg_labels}}'

