#!/bin/bash
#
# Title:      PTS Updater
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: 'Register Path'
      shell: 'cat /var/plexguide/pg.number'
      register: serverid

    - name: 'Check folder exist'
      stat:
        path: /opt/plexguide/menu/pg.yml
      register: stat_result

    - name: 'Remove old PTS folder'
      shell: 'rm -rf /opt/plexguide'

    - name: 'Installing Version {{serverid.stdout}}'
      git:
        repo: 'https://github.com/MHA-Team/PTS-Team'
        dest: '/opt/plexguide'
        version: '{{serverid.stdout}}'
        force: yes
      when: not serverid.stdout == "edge"
      ignore_errors: True

    - stat:
        path: /opt/plexguide/menu
      register: p
    - debug:
        msg: "Path exists and PTS folder are pulled"
      when: p.stat.isdir is defined and p.stat.isdir

    - name: Remove .githube folder and .git files
      file: 'path={{item}} state=absent mode=0775 owner=1000 group=1000'
      with_items:
        - '/opt/plexguide/LICENSE'
        - '/opt/plexguide/README.md'

    - name: 'Setting ownership on PTS Folder'
      shell: 'chown -cR 1000:1000 /opt/plexguide 1>/dev/null 2>&1'

    - name: 'Setting permissions on PTS Folder'
      shell: 'chmod -cR 775 /opt/plexguide 1>/dev/null 2>&1'

    - name: 'Stops First Time Run'
      shell: 'touch /var/plexguide/ask.yes'
      register: program

    - cron:
        name: Build a Cron Job - autoupdate
        special_time: 'weekly'
        job: 'autoupdatepts 1>/dev/null 2>&1'
        state: absent

    - cron:
        name: Build a Cron Job - autoupdate
        special_time: 'weekly'
        job: 'sudo autoupdatepts 1>/dev/null 2>&1'
        state: absent

    - cron:
        name: Build a Cron Job - autoupdate
        special_time: 'daily'
        job: 'sudo autoupdatepts 1>/dev/null 2>&1'
        state: absent
