#!/bin/bash
#
# Title:      PTSUpdate Manual
# Author(s):  MrDoob for PTS
# GNU:        General Public License v3.0
################################################################################
rm -rf /opt/ptsupdate 1>/dev/null 2>&1
mkdir -p /opt/ptsupdate 1>/dev/null 2>&1
git clone https://github.com/xkronusx/FA-Blitz.git /opt/FA-Blitz-Files 1>/dev/null 2>&1
mv /opt/FA-Blitz-Files/PTS-Update-master/* /opt/ptsupdate
chown -cR 1000:1000 /opt/ptsupdate 1>/dev/null 2>&1
chmod -cR 775 /opt/ptsupdate 1>/dev/null 2>&1

source /opt/ptsupdate/autoupdate/update.sh

start0
