#!/bin/bash
#
# Title:      PTS Install base
# Author(s):  MrDoobPG
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: 'Check folder exist'
      stat:
        path: /opt/pgstage
      register: stat_result
    - debug:
        msg: "PTS Check for missing pull"

    - name: 'Cloning PTS Install files'
      git:
        repo: 'https://github.com/xkronusx/FA-Blitz'
        dest: /opt/FA-Blitz-Files
        clone: yes
        version: 'master'
        force: yes
        update: yes
      become: yes

    - name: 'Cloning PTS Install files2'
      command: mv /opt/FA-Blitz-Files/Install-master/ /opt/plexguide

    - stat:
        path: /opt/pgstage
      register: p
    - debug:
        msg: "Path exists and PTS folder are pulled"
      when: p.stat.isdir is defined and p.stat.isdir

    - name: Remove .githube folder and .git files
      file: 'path={{item}} state=absent mode=0775 owner=1000 group=1000'
      with_items:
        - '/opt/pgstage/.git'
        - '/opt/pgstage/.github'
        - '/opt/pgstage/.gitignore'
        - '/opt/pgstage/LICENSE'
        - '/opt/pgstage/README.md'

    - name: Check if Image Variable Exists
      stat:
        path: '/opt/communityapps'
      register: pathcheck

    - name: 'Transfer Image Variable'
      shell: 'rm -rf /opt/communityapps'
      when: pathcheck.stat.exists

    - name: Cloning Community Apps
      shell: 'mv /opt/FA-Blitz-Files/Apps-Community-master/* /opt/communityapps'

    - name: Set Permission and Owner
      shell: 'chown -R 1000:1000 /opt/communityapps && chmod -R 775 /opt/communityapps'

    - name: Check if Image Variable Exists
      stat:
        path: '/opt/coreapps'
      register: pathcheck

    - name: 'Transfer Image Variable'
      shell: 'rm -rf /opt/coreapps'
      when: pathcheck.stat.exists

    - name: Cloning Core Apps
      shell: 'mv /opt/FA-Blitz-Files/Apps-Core-master/* /opt/coreapps'

    - name: Set Permission and Owner
      shell: 'chown -R 1000:1000 /opt/coreapps && chmod -R 775 /opt/coreapps'
