#!/bin/bash
#
# Title:      PTS Install base folders
# Author(s):  MrDoobPG
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Basic Directories
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true'
      with_items:
        - '/opt/appdata/plexguide'
        - '/opt/appdata/plexguide/emergency'
        - '/opt/communityapps'
        - '/opt/mycontainers'
        - '/opt/coreapps'
        - '/var/plexguide'
        - '/opt/plexguide'
        - '/opt/pgstage'
        - '/opt/ptsupdate'
      ignore_errors: yes
